using NetAndroidDebugger.Core;
using NetAndroidDebugger.Frontends;

namespace NetAndroidDebugger.Tests;

/// <summary>
/// The launch configuration reader. No device: this is about what a real <c>.vscode/launch.json</c>
/// contains and about failing in a way that names the file and the mistake, because a configuration
/// that is silently misread launches the wrong app on the wrong device.
/// </summary>
public sealed class LaunchConfigTests
{
    /// <summary>A throwaway project folder holding a .vscode/launch.json, as VS Code would.</summary>
    private sealed class TempWorkspace : IDisposable
    {
        private readonly DirectoryInfo _root = Directory.CreateTempSubdirectory("nad-cfg-");

        public string Root => _root.FullName;

        public string Write(string json, string relativePath = ".vscode/launch.json")
        {
            var path = Path.Combine(Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, json);
            return path;
        }

        public void Dispose() => _root.Delete(recursive: true);
    }

    /// <summary>
    /// What VS Code actually writes: a comment header, a trailing comma, and paths through
    /// ${workspaceFolder}. All three are ordinary, and all three break a plain JSON reader.
    /// </summary>
    [Fact]
    public void AFileAsVsCodeWritesIt_IsRead_CommentsTrailingCommasAndVariablesIncluded()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            {
              // Generated by the .NET for Android extension.
              "version": "0.2.0",
              "configurations": [
                {
                  "type": "net-android",
                  "request": "launch",
                  "name": "App.Droid on the tablet",
                  "deviceSerial": "emulator-5554",
                  "packageName": "App.Droid",
                  "projectPath": "${workspaceFolder}/src/App.Droid/App.Droid.csproj",
                  "deploy": true,
                  "keepPropertyFresh": true,
                  "basePort": 10500,
                },
              ]
            }
            """);

        var config = LaunchConfigFile.Read(file);

        Assert.Equal("App.Droid on the tablet", config.Name);
        Assert.Equal("emulator-5554", config.DeviceSerial);
        Assert.Equal("App.Droid", config.PackageName);
        Assert.Equal(Path.Combine(ws.Root, "src", "App.Droid", "App.Droid.csproj"), config.ProjectPath);
        Assert.True(config.Deploy);
        Assert.True(config.KeepPropertyFresh);
        Assert.Equal(10500, config.BasePort);
        // Everything not stated keeps the same default as launch_app, not some second set of defaults.
        Assert.Equal("Debug", config.Configuration);
        Assert.Null(config.ActivityName);
        Assert.Empty(config.Rules);
    }

    /// <summary>
    /// ${workspaceFolder} means the project, not the .vscode folder the file sits in. Getting this
    /// wrong resolves every relative path one level too deep, and the error surfaces as a missing
    /// .csproj much later.
    /// </summary>
    [Fact]
    public void WorkspaceFolder_IsTheProjectRoot_NotTheDotVscodeFolderHoldingTheFile()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ {
                "type": "net-android", "name": "app",
                "deviceSerial": "emulator-5554", "packageName": "com.example.app",
                "projectPath": "App/App.csproj"
            } ] }
            """);

        var config = LaunchConfigFile.Read(file);

        Assert.Equal(Path.Combine(ws.Root, "App", "App.csproj"), config.ProjectPath);
    }

    [Fact]
    public void ConfigName_PicksTheConfiguration_AndAnUnknownOneListsWhatTheFileHolds()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [
              { "type": "net-android", "name": "phone",  "deviceSerial": "RF8N",          "packageName": "com.example.app" },
              { "type": "net-android", "name": "emulator", "deviceSerial": "emulator-5554", "packageName": "com.example.app" }
            ] }
            """);

        Assert.Equal("emulator-5554", LaunchConfigFile.Read(file, "emulator").DeviceSerial);
        Assert.Equal("RF8N", LaunchConfigFile.Read(file, "phone").DeviceSerial);
        // No name given: the first one, as VS Code's own list does.
        Assert.Equal("phone", LaunchConfigFile.Read(file).Name);

        var wrong = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(file, "tablet"));
        Assert.Contains("'phone'", wrong.Message);
        Assert.Contains("'emulator'", wrong.Message);
    }

    /// <summary>
    /// A launch.json normally holds configurations for several debuggers. Ours are the only ones we
    /// can honour, and saying which type was found beats "no configuration".
    /// </summary>
    [Fact]
    public void ConfigurationsOfAnotherDebugger_AreSkipped_AndNamedIfAskedForByName()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [
              { "type": "node",        "name": "backend", "program": "server.js" },
              { "type": "net-android", "name": "app", "deviceSerial": "emulator-5554", "packageName": "com.example.app" }
            ] }
            """);

        Assert.Equal("app", LaunchConfigFile.Read(file).Name);

        var byName = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(file, "backend"));
        Assert.Contains("type 'node'", byName.Message);

        var noneOfOurs = ws.Write("""
            { "configurations": [ { "type": "node", "name": "backend", "program": "server.js" } ] }
            """, "other/launch.json");
        var missing = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(noneOfOurs));
        Assert.Contains("net-android", missing.Message);
        Assert.Contains("'backend'", missing.Message);
    }

    /// <summary>
    /// ${command:...} is how VS Code asks the user to pick a device. Outside VS Code nobody can
    /// answer it, and passing it through would reach adb as a device serial.
    /// </summary>
    [Fact]
    public void VariablesOnlyVsCodeCanAnswer_AreRefusedByName()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ {
                "type": "net-android", "name": "app",
                "deviceSerial": "${command:pickAndroidDevice}", "packageName": "com.example.app"
            } ] }
            """);

        var ex = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(file));
        Assert.Contains("${command:pickAndroidDevice}", ex.Message);
        Assert.Contains("VS Code", ex.Message);
    }

    [Fact]
    public void EnvironmentVariables_AreExpanded()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ {
                "type": "net-android", "name": "app",
                "deviceSerial": "${env:NAD_TEST_SERIAL}", "packageName": "com.example.app"
            } ] }
            """);

        Environment.SetEnvironmentVariable("NAD_TEST_SERIAL", "emulator-5554");
        try
        {
            Assert.Equal("emulator-5554", LaunchConfigFile.Read(file).DeviceSerial);
        }
        finally
        {
            Environment.SetEnvironmentVariable("NAD_TEST_SERIAL", null);
        }
    }

    /// <summary>
    /// Only the app's identity is mandatory. The device is not: a serial names a machine, so
    /// committing one to a shared file makes it wrong on everybody else's desk — the caller resolves
    /// it from the call, NAD_DEVICE_SERIAL, or the only ready device.
    /// </summary>
    [Fact]
    public void AConfigurationMissingThePackage_SaysWhichOneAndWhatIsMissing()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ { "type": "net-android", "name": "app", "deviceSerial": "emulator-5554" } ] }
            """);

        var ex = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(file));
        Assert.Contains("'app'", ex.Message);
        Assert.Contains("packageName", ex.Message);
    }

    [Fact]
    public void AConfigurationWithoutADeviceSerial_IsValid_AndLeavesItToTheCaller()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ { "type": "net-android", "name": "app", "packageName": "com.example.app" } ] }
            """);

        var config = LaunchConfigFile.Read(file);

        Assert.Equal("com.example.app", config.PackageName);
        Assert.Null(config.DeviceSerial);
    }

    /// <summary>
    /// The point of putting rules in the launch configuration: "this app raises these exceptions on
    /// purpose" is a fact about the app, so it belongs in the app's repository rather than in one
    /// person's profile.
    /// </summary>
    [Fact]
    public void ExceptionRules_TravelWithTheConfiguration()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ {
                "type": "net-android", "name": "app",
                "deviceSerial": "emulator-5554", "packageName": "com.example.app",
                "exceptionRules": [
                  { "typeContains": "Mqtt", "action": "ignore" },
                  { "action": "break" }
                ],
                "globalExceptionRulesPath": "${workspaceFolder}/team-rules.json"
            } ] }
            """);

        var config = LaunchConfigFile.Read(file);

        Assert.Equal(2, config.Rules.Count);
        Assert.Equal(ExceptionAction.Ignore, config.Rules[0].Action);
        Assert.Equal("Mqtt", config.Rules[0].TypeContains);
        Assert.Equal(ExceptionAction.Break, config.Rules[1].Action);
        Assert.True(config.UseGlobalExceptionRules);
        Assert.Equal(Path.Combine(ws.Root, "team-rules.json"), config.GlobalExceptionRulesPath);
    }

    /// <summary>A bad rule is reported against the configuration holding it, not as "rule 2".</summary>
    [Fact]
    public void ABadExceptionRule_NamesTheConfigurationItIsIn()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "configurations": [ {
                "type": "net-android", "name": "app",
                "deviceSerial": "emulator-5554", "packageName": "com.example.app",
                "exceptionRules": [ { "typeContains": "Mqtt", "action": "shrug" } ]
            } ] }
            """);

        var ex = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(file));
        Assert.Contains("'app'", ex.Message);
        Assert.Contains("shrug", ex.Message);
    }

    /// <summary>
    /// Nobody using this outside VS Code should have to write the launch.json envelope: a single
    /// object saying which app on which device is a complete configuration.
    /// </summary>
    [Fact]
    public void ASingleHandWrittenObject_IsAConfiguration()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("""
            { "deviceSerial": "emulator-5554", "packageName": "com.example.app" }
            """, "debug.json");

        var config = LaunchConfigFile.Read(file);

        Assert.Equal("com.example.app", config.PackageName);
        Assert.Equal("(unnamed)", config.Name);
    }

    [Fact]
    public void AMissingFile_SaysWhereItLooked()
    {
        using var ws = new TempWorkspace();

        var ex = Assert.Throws<FileNotFoundException>(() => LaunchConfigFile.Read(workspaceFolder: ws.Root));

        Assert.Contains(Path.Combine(ws.Root, ".vscode", "launch.json"), ex.Message);
    }

    [Fact]
    public void AFileThatIsNotJson_NamesTheFile()
    {
        using var ws = new TempWorkspace();
        var file = ws.Write("{ this is not json");

        var ex = Assert.Throws<FormatException>(() => LaunchConfigFile.Read(file));

        Assert.Contains(file, ex.Message);
    }
}
